import { useEffect, useMemo, useState } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { usePortfolio } from "./hooks/usePortfolio";
import { usePools } from "./hooks/usePools";
import { useZapIn, useZapOut } from "./hooks/useZap";
import { chatWithAI } from "./lib/api";

const money=n=>Number.isFinite(Number(n))?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:Number(n)>1000?0:2}).format(Number(n)):"$0";
const compact=n=>Number.isFinite(Number(n))?new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(Number(n)):"—";
const pct=n=>Number.isFinite(Number(n))?`${Number(n)>=0?"+":""}${Number(n).toFixed(2)}%`:"—";
const pair=p=>p?.name||p?.pool_name||`${p?.token0_symbol||p?.tokenName0||"SOL"} / ${p?.token1_symbol||p?.tokenName1||"USDC"}`;
const poolId=p=>p?.id||p?.pool_id||p?.address||p?.poolAddress;

function Mark(){return <div className="mark"><span>LP</span><i/></div>}
function Arrow(){return <span aria-hidden>↗</span>}

function Landing({onEnter}){
  return <main className="landing">
    <nav className="land-nav"><div className="brand"><Mark/><span>LP Copilot</span></div><div className="nav-mid"><a href="#product">Product</a><a href="#method">Method</a><a href="#build">Build</a></div><button className="text-btn" onClick={onEnter}>Open workspace <Arrow/></button></nav>
    <section className="hero">
      <div className="hero-kicker"><span className="pulse"/> BUILT ON SOLANA · LONDON 2026</div>
      <h1>Liquidity decisions,<br/><em>without the noise.</em></h1>
      <p className="hero-copy">LP Copilot turns fragmented pool data and wallet positions into clear, reviewable liquidity strategies. Understand the why, inspect the risk, then execute on-chain.</p>
      <div className="hero-actions"><button className="primary" onClick={onEnter}>Launch LP Copilot <Arrow/></button><a className="secondary" href="#product">See how it works ↓</a></div>
      <div className="hero-stage" aria-label="LP Copilot product preview">
        <div className="stage-top"><span>PORTFOLIO INTELLIGENCE</span><span className="live"><i/> LIVE</span></div>
        <div className="stage-grid">
          <div className="stage-score"><small>Liquidity health</small><strong>82</strong><span>/100</span><div className="score-line"><i style={{width:"82%"}}/></div><p>Balanced exposure. One position needs attention.</p></div>
          <div className="stage-thought"><small>COPILOT NOTE · 01</small><h3>Your SOL/USDC range is doing its job.</h3><p>Fee capture remains healthy relative to current range exposure. No urgent rebalance suggested.</p><button onClick={onEnter}>Inspect reasoning <Arrow/></button></div>
          <div className="stage-pool"><small>OPPORTUNITY RADAR</small><div><b>SOL / USDC</b><span>87</span></div><div><b>JUP / USDC</b><span>74</span></div><div><b>JITOSOL / SOL</b><span>69</span></div><p>Scores are decision-support signals, not return forecasts.</p></div>
        </div>
      </div>
    </section>
    <section id="product" className="manifesto"><p className="eyebrow">THE PRODUCT</p><h2>Most LP tools show you <span>more data.</span><br/>We built one that helps you decide.</h2><div className="manifest-grid"><article><b>01</b><h3>Read the portfolio</h3><p>Bring positions, fees, PnL and range exposure into one legible view.</p></article><article><b>02</b><h3>Reason with context</h3><p>Claude turns portfolio and pool context into plain-English strategy and risk notes.</p></article><article><b>03</b><h3>Act, with control</h3><p>Prepare Meteora liquidity actions, inspect them, then approve from your own wallet.</p></article></div></section>
    <section id="method" className="principle"><div><p className="eyebrow">OUR PRINCIPLE</p><h2>AI should explain the trade-off.<br/><i>Your wallet makes the decision.</i></h2></div><p>LP Copilot never treats an AI answer as authority. Recommendations are grounded in available portfolio and pool data, risks stay visible, and every on-chain action requires explicit wallet approval.</p></section>
    <section id="build" className="build"><div><p className="eyebrow">BUILD FOR BREAKPOINT</p><h2>Built in the open.<br/>Tested with real wallets.</h2></div><div className="build-card"><span>SUPERTEAM UK · 2026</span><p>Designed for the path from working product to recurring use: instrument the core loop, watch where LPs find value, and improve from evidence rather than assumptions.</p><button className="primary" onClick={onEnter}>Enter the workspace <Arrow/></button></div></section>
    <footer><div className="brand"><Mark/><span>LP Copilot</span></div><span>Solana liquidity intelligence · 2026</span></footer>
  </main>
}

function Sidebar({page,setPage,onHome}){const items=[["overview","Overview"],["radar","Opportunity radar"],["strategy","Strategy studio"],["activity","Activity"]];return <aside className="sidebar"><button className="side-brand" onClick={onHome}><Mark/><span>LP Copilot</span></button><div className="side-label">WORKSPACE</div>{items.map(([id,label])=><button key={id} className={`side-item ${page===id?"active":""}`} onClick={()=>setPage(id)}><i/>{label}</button>)}<div className="side-spacer"/><div className="side-note"><span>CLAUDE INTELLIGENCE</span><p>Reasoning is advisory. Verify every action before signing.</p></div><button className="side-home" onClick={onHome}>← Product home</button></aside>}

function EmptyWallet(){return <div className="empty-wallet"><div className="orb"><span>LP</span></div><p className="eyebrow">YOUR WORKSPACE</p><h2>Start with your wallet.<br/><i>Keep control of every action.</i></h2><p>Connect a Solana wallet to read LP positions, surface portfolio context and prepare liquidity actions. LP Copilot never takes custody.</p><WalletMultiButton/><small>Read-only until you explicitly approve a transaction.</small></div>}

function Stat({label,value,note,tone=""}){return <div className="stat"><span>{label}</span><strong className={tone}>{value}</strong><small>{note}</small></div>}
function Insight({x}){return <div className={`insight ${x.type||"info"}`}><span>{x.type==="warn"?"ATTENTION":x.type==="good"?"HEALTHY":"CONTEXT"}</span><h4>{x.title}</h4><p>{x.message}</p>{x.action&&<small>{x.action} →</small>}</div>}

function Overview({portfolio,onPage,onZapOut}){const {positions=[],overview,aiInsights=[],healthScore,summary,loading}=portfolio;const tvl=positions.reduce((s,p)=>s+(Number(p.currentValue)||0),0);const fees=positions.reduce((s,p)=>s+(Number(p.collectedFee)||0)+(Number(p.unCollectedFee)||0),0);const pnl=Number(overview?.total_pnl?.ALL)||0;return <div className="page"><div className="page-head"><div><p className="eyebrow">PORTFOLIO / LIVE</p><h1>Your liquidity, in context.</h1><p>{summary||"Portfolio data and decision support in one workspace."}</p></div><button className="outline" onClick={()=>onPage("strategy")}>Ask Copilot <Arrow/></button></div>{loading?<div className="loading-line">Reading on-chain positions…</div>:<><div className="stats"><Stat label="Liquidity deployed" value={money(tvl)} note={`${positions.length} open position${positions.length===1?"":"s"}`}/><Stat label="Fees captured" value={money(fees)} note="Across open positions" tone="positive"/><Stat label="Net PnL" value={money(pnl)} note="Reported portfolio PnL" tone={pnl>=0?"positive":"negative"}/><Stat label="Liquidity health" value={healthScore==null?"—":`${healthScore}/100`} note="Claude-supported heuristic"/></div><div className="overview-grid"><section className="panel positions"><div className="panel-head"><div><span>OPEN POSITIONS</span><h3>Where capital is working</h3></div><button onClick={()=>onPage("radar")}>Discover pools <Arrow/></button></div>{positions.length?positions.slice(0,5).map((p,i)=><div className="position-row" key={p.id||i}><div className="token-pair"><div className="coin">{(p.tokenName0||"S")[0]}</div><div><b>{pair(p)}</b><span>{p.protocol||"Meteora"}</span></div></div><div><small>VALUE</small><b>{money(p.currentValue)}</b></div><div><small>FEES</small><b>{money((Number(p.collectedFee)||0)+(Number(p.unCollectedFee)||0))}</b></div><button className="mini" onClick={()=>onZapOut(p)}>Manage</button></div>):<div className="panel-empty">No Meteora LP positions were returned for this wallet.</div>}</section><section className="panel intelligence"><div className="panel-head"><div><span>COPILOT INTELLIGENCE</span><h3>What deserves attention</h3></div><div className="claude-badge">C · Claude</div></div><div className="insights">{aiInsights.length?aiInsights.map((x,i)=><Insight key={i} x={x}/>):<div className="panel-empty">Insights appear when portfolio positions are available.</div>}</div></section></div></>}</div>}

function Radar({pools,onZap}){const [risk,setRisk]=useState("balanced");const list=pools.pools||[];return <div className="page"><div className="page-head"><div><p className="eyebrow">OPPORTUNITY RADAR</p><h1>Find signal, not yield bait.</h1><p>Compare live pools with liquidity, volume and risk context visible before you act.</p></div><div className="seg">{["conservative","balanced","aggressive"].map(x=><button key={x} className={risk===x?"on":""} onClick={()=>setRisk(x)}>{x}</button>)}</div></div><section className="panel pool-table"><div className="table-head"><span>POOL</span><span>TVL</span><span>24H VOLUME</span><span>APR / SIGNAL</span><span>RISK</span><span/></div>{pools.loading?<div className="panel-empty">Scanning Solana liquidity…</div>:list.slice(0,12).map((p,i)=>{const tvl=Number(p.tvl||p.liquidity||0),vol=Number(p.vol_24h||p.volume_24h||0),apr=Number(p.apr||p.apy||0);const riskLabel=tvl>2e6?"Lower":tvl>250000?"Medium":"Higher";return <div className="table-row" key={poolId(p)||i}><div className="pool-name"><div className="coin">{pair(p)[0]}</div><div><b>{pair(p)}</b><small>Meteora · Solana</small></div></div><span>{money(tvl)}</span><span>{money(vol)}</span><span className="signal">{apr?pct(apr):"Data-led"}</span><span><i className={`risk ${riskLabel.toLowerCase()}`}/>{riskLabel}</span><button className="mini" onClick={()=>onZap(p)}>Add liquidity</button></div>})}</section><p className="disclaimer">Pool metrics come from the connected liquidity data provider. “Risk” is a simple liquidity heuristic, not financial advice or a prediction of returns.</p></div>}

function Strategy({portfolio}){const [q,setQ]=useState("Review my portfolio and tell me the single most important liquidity decision to consider next.");const [reply,setReply]=useState("");const [busy,setBusy]=useState(false);async function ask(){setBusy(true);setReply("");try{const r=await chatWithAI(q,{positions:portfolio.positions,overview:portfolio.overview});setReply(r.reply)}catch(e){setReply(`Copilot unavailable: ${e.message}`)}finally{setBusy(false)}}return <div className="page"><div className="page-head"><div><p className="eyebrow">STRATEGY STUDIO</p><h1>Ask in plain English.<br/><i>Get a decision you can inspect.</i></h1><p>Claude reasons over the portfolio context available to LP Copilot. It does not sign or submit transactions.</p></div><div className="claude-badge large">C · Powered by Claude</div></div><div className="studio"><div className="prompt-box"><label>WHAT ARE YOU TRYING TO DO?</label><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="e.g. I have 5 SOL and prefer lower volatility. What should I consider?"/><div className="quick"><button onClick={()=>setQ("Where is my portfolio most exposed right now?")}>Find my biggest risk</button><button onClick={()=>setQ("Explain my LP portfolio like I am reviewing it with an investment committee.")}>Explain my portfolio</button><button onClick={()=>setQ("What should I check before adding more liquidity?")}>Pre-deposit checklist</button></div><button className="primary ask" disabled={busy||!q.trim()} onClick={ask}>{busy?"Reasoning with portfolio context…":"Generate strategy →"}</button></div><div className="answer"><div className="answer-top"><span>COPILOT RESPONSE</span><span>{portfolio.positions?.length||0} POSITIONS IN CONTEXT</span></div>{reply?<div className="answer-copy">{reply}</div>:<div className="answer-empty"><div className="answer-mark">C</div><h3>Strategy starts with context.</h3><p>Ask about risk, position concentration, range management or what to review before an on-chain action.</p></div>}<div className="guardrail"><b>Human approval stays in the loop.</b><span>Recommendations are decision support, not guaranteed outcomes. Verify data and transaction details before signing.</span></div></div></div></div>}

function Activity({logs=[]}){return <div className="page"><div className="page-head"><div><p className="eyebrow">ACTIVITY / PROOF</p><h1>From recommendation to chain.</h1><p>A legible record of portfolio activity and execution evidence.</p></div></div><section className="panel activity">{logs.length?logs.slice(0,20).map((l,i)=><div className="activity-row" key={l.signature||i}><span className="activity-dot"/><div><b>{l.type||l.action||"Liquidity activity"}</b><small>{l.createdAt||l.timestamp||"On-chain record"}</small></div><span>{l.pool_name||l.pool||"Solana"}</span>{l.signature?<a href={`https://solscan.io/tx/${l.signature}`} target="_blank" rel="noreferrer">Proof <Arrow/></a>:<span>Recorded</span>}</div>):<div className="panel-empty">On-chain LP activity will appear here when available.</div>}</section></div>}

function ZapModal({pool,position,onClose,zapIn,zapOut}){const [amount,setAmount]=useState("0.25");const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function go(){setBusy(true);setError("");try{if(pool)await zapIn.zapIn({poolId:poolId(pool),inputSOL:Number(amount)});else await zapOut.zapOut({positionId:position.id,bps:10000,output:"allBaseToken"});onClose()}catch(e){setError(e.message)}finally{setBusy(false)}}return <div className="modal-back" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><button className="modal-x" onClick={onClose}>×</button><p className="eyebrow">REVIEW ACTION</p><h2>{pool?`Add liquidity to ${pair(pool)}`:`Manage ${pair(position)}`}</h2><p>{pool?"LP Copilot prepares the transaction. Your wallet remains the final approval layer.":"Withdraw this position to SOL using the connected liquidity execution flow."}</p>{pool&&<label className="amount">SOL AMOUNT<input type="number" min="0" step="0.05" value={amount} onChange={e=>setAmount(e.target.value)}/></label>}<div className="review"><span>Execution</span><b>Meteora + Jito</b><span>Approval</span><b>Connected wallet</b><span>Slippage guard</span><b>5.00% default</b></div>{error&&<div className="error">{error}</div>}<button className="primary full" onClick={go} disabled={busy}>{busy?"Waiting for wallet / network…":pool?"Prepare & approve transaction →":"Approve withdrawal →"}</button><small className="modal-note">Inspect every wallet prompt before signing. Transactions are irreversible once confirmed.</small></div></div>}

function Workspace({onHome}){const wallet=useWallet();const owner=wallet.publicKey?.toBase58();const portfolio=usePortfolio(owner);const pools=usePools();const zapIn=useZapIn();const zapOut=useZapOut();const [page,setPage]=useState("overview");const [modal,setModal]=useState(null);return <div className="workspace"><Sidebar page={page} setPage={setPage} onHome={onHome}/><div className="work-main"><header className="work-top"><div><span className="network"><i/> SOLANA MAINNET</span></div><WalletMultiButton/></header>{!owner?<EmptyWallet/>:<>{page==="overview"&&<Overview portfolio={portfolio} onPage={setPage} onZapOut={p=>setModal({position:p})}/>} {page==="radar"&&<Radar pools={pools} onZap={p=>setModal({pool:p})}/>} {page==="strategy"&&<Strategy portfolio={portfolio}/>} {page==="activity"&&<Activity logs={portfolio.logs}/>}</>}{modal&&<ZapModal {...modal} onClose={()=>setModal(null)} zapIn={zapIn} zapOut={zapOut}/>}</div></div>}

export default function App(){const [mode,setMode]=useState(()=>location.hash==="#app"?"app":"home");useEffect(()=>{const f=()=>setMode(location.hash==="#app"?"app":"home");addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[]);const enter=()=>{location.hash="app";setMode("app")};const home=()=>{history.pushState(null,"",location.pathname);setMode("home");window.scrollTo(0,0)};return mode==="home"?<Landing onEnter={enter}/>:<Workspace onHome={home}/>}
